name: Publish Client Android Release Candidate

on: 
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "SHA of commit to publish (example: 2ac8bd4a915a7c8a3e3a63081d72da33baa9ea7e)"
        required: true

jobs:
  release:
    name: Publish Client Android Release Candidate
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      RELEASES_REPOSITORY: ${{ secrets.RELEASES_REPOSITORY }}
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install Node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 16

    - name: Install NPM Dependencies
      run: npm ci

    - name: Tag Release Commit
      run: |
        git config --global user.name "OutlineBot"
        git config --global user.email "outlinebot@users.noreply.github.com"
        git tag "android-$(node scripts/get_version.mjs android)"
        git push origin "android-$(node scripts/get_version.mjs android)"

    - name: Download Release Candidate
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_release_candidates.yml
        commit: ${{ github.event.inputs.commit_sha }}
        name: client_android_release_${{ github.event.inputs.commit_sha }}
        path: client_android_release

    - name: Checkout Releases Repository
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ env.RELEASES_REPOSITORY }}
        token: ${{ env.GITHUB_TOKEN }}
        path: outline-releases

    - name: Push to Releases Repository
      run: |
        RELEASE_VERSION="$(node scripts/get_version.mjs android)"
        cp client_android_release/bundle/release/app-release.aab outline-releases/client/Outline.aab
        cd outline-releases
        git checkout master
        git add client/Outline.aab
        git commit -m "Release android client ${RELEASE_VERSION}"
        git tag "android-${RELEASE_VERSION}"
        git push origin "android-${RELEASE_VERSION}"
        git push origin master
